#!/usr/bin/env python3

import rospy
from std_msgs.msg import Float64
from simple_arm.srv import *

if __name__ == "__main__":
    rospy.init_node("arm_mover_client")
    rospy.wait_for_service("/arm_mover/safe_move")

    try:
        client = rospy.ServiceProxy("/arm_mover/safe_move", GoToPosition)
        client(1.57, 1.57)

    except rospy.ServiceException as e:
        
        rospy.logwarn("Service failed: " + str(e))